name: Package Build

on:
  push:
    branches:
      - testing/add-tests
  pull_request:
    branches:
      - main

jobs:
  build-package-python3:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python-ver: ['3.12', '3.11', '3.10', '3.9']
    
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      # Setup Python (faster than using Python container)
      - name: Install Python ${{ matrix.python-ver }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-ver }}

      - name: Setup dev environment
        run: make setup

      - name: Build package with poetry
        run: make package
